import type { Locale } from '@/lib/translations';

export type ResearchSection = { id: string; title: string; paragraphs: string[] };
export type Reference = { id: string; title: string; authors: string; publication: string; identifier: string; href: string; supports: string };
type SourceMetadata = Omit<Reference, 'supports'> & { supports: Record<Locale, string> };
export type ResearchContent = {
  eyebrow: string; title: string; summary: string; reviewed: string; contents: string; methodology: string;
  sequence: Array<{ title: string; detail: string }>;
  sections: ResearchSection[]; detailsTitle: string; details: string[]; detailsNote: string;
  referencesTitle: string; referencesIntro: string; references: Reference[];
  disclaimerTitle: string; disclaimer: string; sourceLink: string;
};

const sources: SourceMetadata[] = [
  { id: 'who', title: 'Obesity and overweight', authors: 'World Health Organization', publication: 'WHO fact sheet', identifier: 'WHO', href: 'https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight', supports: { en: 'BMI screening and classification context; BMI is not a diagnosis or direct measure of body fat.', vi: 'Bối cảnh sàng lọc và phân loại BMI; BMI không phải chẩn đoán hoặc phép đo trực tiếp lượng mỡ cơ thể.' } },
  { id: 'mifflin', title: 'A new predictive equation for resting energy expenditure in healthy individuals', authors: 'Mifflin MD et al.', publication: 'American Journal of Clinical Nutrition, 1990', identifier: 'PMID 2305711 · DOI 10.1093/ajcn/51.2.241', href: 'https://pubmed.ncbi.nlm.nih.gov/2305711/', supports: { en: 'Context for the Mifflin–St Jeor predictive equation.', vi: 'Bối cảnh tham khảo cho phương trình dự đoán Mifflin–St Jeor.' } },
  { id: 'morton', title: 'A systematic review, meta-analysis and meta-regression of protein supplementation', authors: 'Morton RW et al.', publication: 'British Journal of Sports Medicine, 2018', identifier: 'PMID 28698222', href: 'https://pubmed.ncbi.nlm.nih.gov/28698222/', supports: { en: 'Protein-intake context; it does not validate every Nutree macro rule.', vi: 'Bối cảnh về lượng protein; không xác thực mọi quy tắc macro của Nutree.' } },
  { id: 'kerksick', title: 'ISSN exercise & sports nutrition review update: research & recommendations', authors: 'Kerksick CM et al.', publication: 'Journal of the International Society of Sports Nutrition, 2018', identifier: 'PMID 30068354', href: 'https://pubmed.ncbi.nlm.nih.gov/30068354/', supports: { en: 'Broad sports-nutrition context, not validation of Nutree’s exact targets.', vi: 'Bối cảnh dinh dưỡng thể thao rộng hơn, không xác thực các mục tiêu chính xác của Nutree.' } },
  { id: 'burke', title: 'Carbohydrates for training and competition', authors: 'Burke LM et al.', publication: 'Journal of Sports Sciences, 2011', identifier: 'PMID 21660838 · DOI 10.1080/02640414.2011.585473', href: 'https://pubmed.ncbi.nlm.nih.gov/21660838/', supports: { en: 'Carbohydrate context for training and competition.', vi: 'Bối cảnh về carbohydrate cho tập luyện và thi đấu.' } },
  { id: 'trexler', title: 'Metabolic adaptation to weight loss: implications for the athlete', authors: 'Trexler ET, Smith-Ryan AE, Norton LE', publication: 'Journal of the International Society of Sports Nutrition, 2014', identifier: 'PMID 24571926 · PMCID PMC3943438 · DOI 10.1186/1550-2783-11-7', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3943438/', supports: { en: 'TDEE components and metabolic-adaptation context; not validation of Nutree redistribution.', vi: 'Bối cảnh về thành phần TDEE và thích nghi chuyển hóa; không xác thực cách Nutree phân bổ lại.' } },
];

const referencesFor = (locale: Locale): Reference[] => sources.map(({ supports, ...source }) => ({ ...source, supports: supports[locale] }));

const en: ResearchContent = {
  eyebrow: 'Evidence transparency', title: 'Science & Sources', summary: 'Nutree’s nutrition estimates are informed by peer-reviewed papers, public-health references, and documented product rules. This page shows the sources, formulas, and limitations behind the app.', reviewed: 'Last reviewed: July 25, 2026', contents: 'On this page', methodology: 'How Nutree estimates targets',
  sequence: [
    { title: 'Profile', detail: 'You provide profile inputs used for estimates.' }, { title: 'Estimated BMR', detail: 'Nutree estimates resting energy expenditure; it does not measure metabolism.' }, { title: 'Activity baseline', detail: 'A job/activity multiplier forms the baseline. Logged movement is handled separately.' }, { title: 'Goal adjustment', detail: 'The app applies a goal-specific product rule to the estimate.' }, { title: 'Macro allocation', detail: 'Protein and fat rules are set first; remaining target calories are assigned to carbohydrate.' }, { title: 'Weekly redistribution', detail: 'Previous logged days can adjust future targets. Today’s eating does not change today’s target.' },
  ],
  sections: [
    { id: 'estimates', title: 'Estimates, not measurements', paragraphs: ['When body-fat percentage is unavailable, Nutree uses the Mifflin–St Jeor equation. When it is available, Nutree uses a Katch–McArdle calculation from lean body mass as an alternative estimate. Neither result is a direct measurement of metabolism, and Nutree does not claim that one branch is more accurate for every person.', 'The baseline also uses a job/activity multiplier for non-exercise activity. Movement you log is credited separately, rather than increasing that baseline.'] },
    { id: 'macros', title: 'Macros and calorie display', paragraphs: ['Nutree starts macro targets with body-weight-based protein rules, applies fat rules, then assigns the remaining target calories to carbohydrate. Published sports-nutrition literature gives useful context for protein and carbohydrate, but it does not validate each product threshold or output.', 'Nutrition-engine calories are derived from macro grams after one-decimal rounding. They are estimates and can differ from food labels, databases, and laboratory measurements.'] },
    { id: 'weekly', title: 'Weekly adaptation', paragraphs: ['Nutree can redistribute a weekly target from consumption logged before the current day. The purpose is to keep future targets aligned with the current weekly budget; it is not a clinical prediction or a validated treatment method.', 'The redistribution keeps protein fixed, adjusts remaining carbohydrate and fat within app bounds, and can apply a BMR-based floor. These are Nutree safeguards and product behavior, not clinically validated guarantees.'] },
    { id: 'bmi', title: 'BMI context and limitations', paragraphs: ['BMI is a weight-to-height screening and classification measure. It is not a diagnosis or a direct measure of body fat.', 'Interpretation can vary with body composition, age, pregnancy, population, and clinical context. Use it as one piece of context, not an individual health conclusion.'] },
  ],
  detailsTitle: 'Calculation details: Nutree product rules', details: ['The full TDEE path applies goal adjustments of −300 kcal for cut, +300 kcal for bulk, and 0 kcal for recomp.', 'The full TDEE path will not set a target below estimated BMR or the app’s sex-specific minimum: 1,200 kcal for female and 1,500 kcal for male profiles.', 'Protein, fat, carbohydrate bounds, daily-change caps, and the 80% standard-daily BMR floor are implementation safeguards. They are not clinical prescriptions or evidence-validated for every user.'], detailsNote: 'These values describe current app behavior and may change. They should not be read as medical advice.',
  referencesTitle: 'Sources', referencesIntro: 'These canonical sources provide context for the bounded claims above. They do not validate every Nutree product rule.', references: referencesFor('en'), disclaimerTitle: 'Medical disclaimer', disclaimer: 'Nutree results are educational estimates, not medical advice, diagnosis, or a treatment plan. Speak with a qualified healthcare professional for medical conditions, pregnancy, an eating-disorder history, medication-related needs, or if you need a target below the floor shown in the app.', sourceLink: 'Open source',
};

const vi: ResearchContent = {
  eyebrow: 'Minh bạch bằng chứng', title: 'Khoa học & nguồn', summary: 'Ước tính dinh dưỡng của Nutree được tham chiếu từ bài báo khoa học, nguồn y tế công cộng và quy tắc sản phẩm được mô tả rõ. Trang này trình bày nguồn, công thức và giới hạn phía sau ứng dụng.', reviewed: 'Cập nhật lần cuối: 25 tháng 7, 2026', contents: 'Nội dung trang', methodology: 'Nutree ước tính mục tiêu như thế nào',
  sequence: [{ title: 'Hồ sơ', detail: 'Bạn cung cấp dữ liệu hồ sơ dùng cho các ước tính.' }, { title: 'BMR ước tính', detail: 'Nutree ước tính năng lượng tiêu hao khi nghỉ, không đo chuyển hóa trực tiếp.' }, { title: 'Mức nền hoạt động', detail: 'Hệ số công việc/hoạt động tạo mức nền; vận động đã ghi nhận được xử lý riêng.' }, { title: 'Điều chỉnh mục tiêu', detail: 'Ứng dụng áp dụng quy tắc sản phẩm theo mục tiêu vào ước tính.' }, { title: 'Phân bổ macro', detail: 'Quy tắc protein và fat được đặt trước; calo mục tiêu còn lại dành cho carbohydrate.' }, { title: 'Phân bổ lại theo tuần', detail: 'Các ngày trước đã ghi nhận có thể điều chỉnh mục tiêu tương lai; ăn hôm nay không đổi ngược mục tiêu hôm nay.' }],
  sections: [{ id: 'estimates', title: 'Ước tính, không phải đo lường', paragraphs: ['Khi không có phần trăm mỡ cơ thể, Nutree dùng phương trình Mifflin–St Jeor. Khi có, Nutree dùng phép tính Katch–McArdle từ khối lượng nạc như một ước tính thay thế. Không kết quả nào là phép đo chuyển hóa trực tiếp; Nutree không khẳng định nhánh nào chính xác hơn cho mọi người.', 'Mức nền cũng dùng hệ số công việc/hoạt động không do tập luyện. Vận động bạn ghi nhận được cộng riêng, thay vì làm tăng mức nền này.'] }, { id: 'macros', title: 'Macro và calo hiển thị', paragraphs: ['Nutree bắt đầu mục tiêu macro bằng quy tắc protein theo cân nặng, áp dụng quy tắc fat, rồi dành phần calo mục tiêu còn lại cho carbohydrate. Tài liệu dinh dưỡng thể thao cung cấp bối cảnh hữu ích, nhưng không xác thực mọi ngưỡng hay đầu ra của sản phẩm.', 'Calo của công cụ dinh dưỡng được suy ra từ gram macro sau khi làm tròn một chữ số thập phân. Đây là ước tính và có thể khác nhãn thực phẩm, cơ sở dữ liệu hoặc phép đo trong phòng thí nghiệm.'] }, { id: 'weekly', title: 'Điều chỉnh theo tuần', paragraphs: ['Nutree có thể phân bổ lại mục tiêu tuần từ lượng tiêu thụ đã ghi nhận trước ngày hiện tại. Mục đích là giữ mục tiêu tương lai phù hợp ngân sách tuần, không phải dự đoán lâm sàng hay phương pháp điều trị đã được xác thực.', 'Việc phân bổ lại giữ protein cố định, điều chỉnh carbohydrate và fat còn lại trong giới hạn ứng dụng, và có thể áp dụng sàn dựa trên BMR. Đây là cơ chế bảo vệ và hành vi của Nutree, không phải cam kết đã được xác thực lâm sàng.'] }, { id: 'bmi', title: 'Bối cảnh và giới hạn của BMI', paragraphs: ['BMI là chỉ số sàng lọc và phân loại dựa trên cân nặng và chiều cao. Đây không phải chẩn đoán hay phép đo trực tiếp lượng mỡ cơ thể.', 'Việc diễn giải có thể khác theo thành phần cơ thể, tuổi, thai kỳ, quần thể và bối cảnh lâm sàng. Hãy xem BMI là một phần thông tin, không phải kết luận sức khỏe cá nhân.'] }],
  detailsTitle: 'Chi tiết tính toán: quy tắc sản phẩm Nutree', details: ['Luồng TDEE đầy đủ áp dụng điều chỉnh mục tiêu: giảm −300 kcal, tăng +300 kcal và recomp 0 kcal.', 'Luồng TDEE đầy đủ không đặt mục tiêu thấp hơn BMR ước tính hoặc mức tối thiểu theo giới của ứng dụng: 1.200 kcal với hồ sơ nữ và 1.500 kcal với hồ sơ nam.', 'Giới hạn protein, fat, carbohydrate, giới hạn thay đổi hằng ngày và sàn BMR bằng 80% mục tiêu ngày chuẩn là các cơ chế triển khai. Chúng không phải đơn thuốc lâm sàng hay được xác thực cho mọi người.'], detailsNote: 'Các giá trị này mô tả hành vi hiện tại của ứng dụng và có thể thay đổi. Không nên xem đây là tư vấn y khoa.',
  referencesTitle: 'Nguồn tham khảo', referencesIntro: 'Các nguồn chính thống này cung cấp bối cảnh cho các nhận định có giới hạn bên trên. Chúng không xác thực mọi quy tắc sản phẩm của Nutree.', references: referencesFor('vi'), disclaimerTitle: 'Tuyên bố miễn trừ y tế', disclaimer: 'Kết quả của Nutree là các ước tính mang tính tham khảo, không phải tư vấn y khoa, chẩn đoán hoặc kế hoạch điều trị. Hãy trao đổi với chuyên gia y tế có chuyên môn nếu bạn có bệnh lý, đang mang thai, có tiền sử rối loạn ăn uống, nhu cầu liên quan đến thuốc, hoặc cần mục tiêu thấp hơn mức sàn hiển thị trong ứng dụng.', sourceLink: 'Mở nguồn',
};

export const researchContent: Record<Locale, ResearchContent> = { en, vi };
